### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by hobnob11** [foxCaves/LEGACY_foxScreen#1]
I feel like you needs some feedback from like a legit source such as git hub.

its supa epic, although can you make it so that some how you can get from the program the URL of the image you uploaded, maby a context menu that has the option "copy last picture's URL to clipboard"

**Comment by Doridian** [comment]
foxScreen already does copy the latest uploaded file to your clipboard as soon as the upload is complete.

**Comment by hobnob11** [comment]
does it copy the file or the foxcav url?

**Comment by Doridian** [comment]
The foxcav.es URL. Copying a direct link is not what I want and hotlinking might be disabled for non-premium users once the premium concept is online :3

**Comment by hobnob11** [comment]
We've got to have money.
