### ISSUE TITLE
Strange white pixels in some screenshots

### ISSUE THREAD

**Issue by Doridian** [foxCaves/LEGACY_foxScreen#2]
Possible causes:
a) Defective default PNG encoder?
    Solutions:
    1) Use JPEG: http://social.msdn.microsoft.com/Forums/en-US/csharpgeneral/thread/fa9cc23e-67b1-474c-aa5b-8e20e1d62c05
b) Issue fixed by new screenshot method?

**Comment by hobnob11** [comment]
https://foxcav.es/view/Jh0mZoddUo

"use a camera" I think the internet is on to something -.-

**Comment by hobnob11** [comment]
"I have no idea what i'm doing meme" This is what i found: http://spazzarama.com/2010/03/29/screen-capture-with-direct3d-api-hooks/

**Comment by gtx5** [comment]
For a further implementation through using DirectX take a look at the code in this project here: https://github.com/spazzarama/Direct3DHook
